<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>
	</PropertyGroup>

	<ItemGroup>
<PackageReference Include="Clipper2" Version="1.5.4" />
<PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.22.1" />
<PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.22.2" />
<PackageReference Include="SkiaSharp" Version="3.119.0" />
<PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.0" />
	</ItemGroup>

	<ItemGroup>
		<None Update="models\ch_ppocr_mobile_v2.0_cls_infer_opt.onnx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="models\en_dict.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="models\en_PP-OCRv3_det_infer_opt.onnx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="models\en_PP-OCRv3_rec_infer_opt.onnx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="models\it_mobile_v2.0_rec_infer.onnx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="models\latin_PP-OCRv3_mobile_rec_infer.onnx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="models\it_dict.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>		
		<None Update="models\latin_dict.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>		
	</ItemGroup>

</Project>
